version: "3.5"
services:
  webapp:
    build:
      context: .
      args:
        APP_SOURCE: "."
        NODE_ENV: "development"

    # NOTE: use 'image' for development
    image: webapp

    # NOTE: add 'command' for development
    command: npm run dev

    # NOTE: add environment file for development
    # env_file: ./conf/vars.env

    ports:
      - "3000:3000"

    # NOTE: the container path must match APP_SOURCE above
    # NOTE: node_modules must be added here so container uses modules from its own volume
    volumes:
      - .:/opt/webapp:rw
      - /opt/webapp/node_modules

    networks:
      - webapp-network

# networking specifics
networks:
  webapp-network:
    driver: bridge
